## Lesson 3: Functions


In [1]:
def my_func():
    print('hello, Data bootcamp learners!')

In [3]:
my_func()

hello, Data bootcamp learners!


## functions with parameter



In [16]:
def myfunc(param,param2='class'):
    print(param,param2)

In [14]:
myfunc

<function __main__.myfunc(param, param2='class')>

In [11]:
myfunc('this is Python Day 2 Training')


this is Python Day 2 Training class


In [15]:
#The myfunc function takes two parameters: param and param2, with a default value of 'class' assigned to param2.

#When the function is called and provided with values for param and param2 (if applicable), it will print these values to the console. For example:

myfunc('Hello', 'world')
# Output: Hello world

myfunc('Hi')
# Output: Hi class
#In the first example, the values of param and param2 are 'Hello' and 'world' respectively, and both are printed to the console. In the second example, only the value of param is provided ('Hi'), and so the default value of 'class' is used for param2.

Hello world
Hi class


In [2]:
# functions with default parameter
# docstrings is just a comment 

def myfunc1(param=5):
    """
    data bootcamp 
    """
    print(param)
    #return param


In [3]:
myfunc1() # here we are not passing any parameter to the function
#since it is already declared as default in function

5


In [8]:
def myfunc1(argument):
    """
    docstring goes here!
    """
    return (argument *5)

In [9]:
x=myfunc1(6)
x
#30

30

## Methods

String Upper and String Lower

In [13]:
st="hello python DAY 2 LeArNerS"

# columns " name"

In [14]:
st.lower()


'hello python day 2 learners'

In [15]:
st.upper()

'HELLO PYTHON DAY 2 LEARNERS'

## Split method



In [16]:
tweet="Go Accenture Technology People ! #DataBootcamp"


In [17]:
#splits with white space. This is the default one
tweet.split()   # \n or \t

['Go', 'Accenture', 'Technology', 'People', '!', '#DataBootcamp']

In [19]:
tweet

'Go Accenture Technology People ! #DataBootcamp'

In [20]:
tweet.lower()

'go accenture technology people ! #databootcamp'

In [21]:
tweet.upper()

'GO ACCENTURE TECHNOLOGY PEOPLE ! #DATABOOTCAMP'

# Understanding Numpy

* Numpy Data types
* Numpy Arrays
* Numpy Indexing and Selection
* Numpy Operations
* Numpy Broadcasting

In [19]:
!pip install numpy 
!pip install matplotlib

In [18]:
# pip install numpy 

In [4]:
import numpy as np

In [23]:
d = np.dtype(np.int32)  
print(d) 

int32


In [24]:
list1=[2,3,4]
arr=np.array(list1)
print("array:",arr)
type(arr)     # array 

array: [2 3 4]


numpy.ndarray

## Numpy Arrays


In [25]:
#integer Array
arr=array([6,7,8])   # array is for numpy [1,2,3]
print("array:",arr)
#type of an array
print("type of arr:",arr.dtype) 

array: [6 7 8]
type of arr: int32


In [26]:
#float Array
arr=array([6,7,8.4])
print("array:",arr)
#type of an array
print("type of arr:",arr.dtype)

array: [6.  7.  8.4]
type of arr: float64


In [27]:
#we can also create a float array with integers by declaring a key word float
arr1=array([7,8,9],float)
print("array:",arr1)
print("type of arr1:",arr1.dtype)

array: [7. 8. 9.]
type of arr1: float64


In [28]:
my_list=[1,2,3]
x=np.array(my_list)   
print(x)
type(x)

[1 2 3]


numpy.ndarray

## Creating Matrix by Arrays



In [2]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
# 3 columns and 3 rows 
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Exercise 

* Make a  3 by 4 matrix 
* Make a 6 by 6 matrix 
* Make a 2 by 6 matrix 

In [30]:
# result indicates that it is two dimensional matrix with 3 columns and 3 row
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
my_matrix=[[1,2,3,4],[5,6,6,7],[8,9,10,11]]
# 4 columns and 3 rows 

In [21]:
my_matrix

[[1, 2, 3, 4], [5, 6, 6, 7], [8, 9, 10, 11]]

In [6]:
# result indicates that it is two dimensional matrix with 4 columns and 3 row
np.array(my_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
my_matrix=[[1,2],[5,6],[8,9,], [3,4]]
# 2 columns and 4 rows 

In [8]:
# result indicates that it is two dimensional matrix with 3 columns and 1 row
np.array(my_matrix)

array([[1, 2],
       [5, 6],
       [8, 9],
       [3, 4]])

In [26]:
list(range(0,11))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [24]:
np.arange(0,11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,33,5)
# 1, 21 is the array 
# 3 is the interval 


array([ 1,  6, 11, 16, 21, 26, 31])

* Way 5- Creating Arrays through Linear space

Linear Space will will create numbers between the given range. Distance between the numbers would be equal. In the example below will create 4 numbers betweeen 0 and 15 with equal distance

In [29]:
np.linspace(0,7,6)  # create 6 numbers 

array([0. , 1.4, 2.8, 4.2, 5.6, 7. ])

In [30]:
np.arange(0,15,4) # intervals 

array([ 0,  4,  8, 12])

In [33]:
#generate 40 numbers between 0 to 15
np.linspace(5,20,200)

array([ 5.        ,  5.07537688,  5.15075377,  5.22613065,  5.30150754,
        5.37688442,  5.45226131,  5.52763819,  5.60301508,  5.67839196,
        5.75376884,  5.82914573,  5.90452261,  5.9798995 ,  6.05527638,
        6.13065327,  6.20603015,  6.28140704,  6.35678392,  6.4321608 ,
        6.50753769,  6.58291457,  6.65829146,  6.73366834,  6.80904523,
        6.88442211,  6.95979899,  7.03517588,  7.11055276,  7.18592965,
        7.26130653,  7.33668342,  7.4120603 ,  7.48743719,  7.56281407,
        7.63819095,  7.71356784,  7.78894472,  7.86432161,  7.93969849,
        8.01507538,  8.09045226,  8.16582915,  8.24120603,  8.31658291,
        8.3919598 ,  8.46733668,  8.54271357,  8.61809045,  8.69346734,
        8.76884422,  8.84422111,  8.91959799,  8.99497487,  9.07035176,
        9.14572864,  9.22110553,  9.29648241,  9.3718593 ,  9.44723618,
        9.52261307,  9.59798995,  9.67336683,  9.74874372,  9.8241206 ,
        9.89949749,  9.97487437, 10.05025126, 10.12562814, 10.20

## Exercise 

* Generate 50 numbers between 0 to 20 


In [20]:
"""if you don't specify the total number of items generated, 
it will automatically generates 50 numbers"""
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [35]:
import numpy as np

# create a 2D array with shape (3,4) filled with zeros
arr1 = np.zeros((3,4))

# create a 2D array with shape (3,4) filled with ones
arr2 = np.ones((3,4))

# create a 1D array with values [1,2,3,4,5]
arr3 = np.array([1,2,3,4,5])

# create a 1D array with values ranging from 0 to 9
arr4 = np.arange(10)

# create a 1D array with values ranging from 0 to 10 with step size 2
arr5 = np.arange(0, 11, 2)

# create a 2D array with shape (3,3) filled with random values between 0 and 1
arr6 = np.random.rand(3,3)

# create a 2D array with shape (3,3) filled with random integers between 0 and 9
arr7 = np.random.randint(0, 10, (3,3))

# add arr1 and arr2 element-wise
arr8 = arr1 + arr2

# multiply arr3 and arr4 element-wise
#arr9 = arr3 * arr4

# find the minimum value in arr6
arr10 = np.min(arr6)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])