## Lesson 3: Functions


In [1]:
def my_func():
    print('hello, Data bootcamp learners!')

In [3]:
my_func()

hello, Data bootcamp learners!


## functions with parameter



In [4]:
def myfunc(param,param2='class'):
    print(param,param2)

In [5]:
myfunc('this is Python Day 2 Training')


this is Python Day 2 Training class


In [2]:
# functions with default parameter
# docstrings is just a comment 

def myfunc1(param=5):
    """
    data bootcamp 
    """
    print(param)
    #return param


In [3]:
myfunc1() # here we are not passing any parameter to the function
#since it is already declared as default in functi

5


In [8]:
def myfunc1(argument):
    """
    docstring goes here!
    """
    return (argument *5)

In [9]:
x=myfunc1(6)
x
#30

30

## Methods

String Upper and String Lower

In [13]:
st="hello python DAY 2 LeArNerS"

# columns " name"

In [14]:
st.lower()


'hello python day 2 learners'

In [15]:
st.upper()

'HELLO PYTHON DAY 2 LEARNERS'

## Split method



In [16]:
tweet="Go Accenture Technology People ! #DataBootcamp"


In [17]:
#splits with white space. This is the default one
tweet.split()   # \n or \t

['Go', 'Accenture', 'Technology', 'People', '!', '#DataBootcamp']

In [19]:
tweet

'Go Accenture Technology People ! #DataBootcamp'

In [20]:
tweet.lower()

'go accenture technology people ! #databootcamp'

In [21]:
tweet.upper()

'GO ACCENTURE TECHNOLOGY PEOPLE ! #DATABOOTCAMP'

# Understanding Numpy

* Numpy Data types
* Numpy Arrays
* Numpy Indexing and Selection
* Numpy Operations
* Numpy Broadcasting

In [4]:
import numpy as np
from numpy  import * # specific library 

In [9]:
import numpy as np 

In [23]:
import numpy as np  
d = np.dtype(np.int32)  
print(d) 

int32


In [24]:
list1=[2,3,4]
arr=np.array(list1)
print("array:",arr)
type(arr)     # array 

array: [2 3 4]


numpy.ndarray

## Numpy Arrays


In [25]:
#integer Array
arr=array([6,7,8])   # array is for numpy [1,2,3]
print("array:",arr)
#type of an array
print("type of arr:",arr.dtype) 

array: [6 7 8]
type of arr: int32


In [26]:
#float Array
arr=array([6,7,8.4])
print("array:",arr)
#type of an array
print("type of arr:",arr.dtype)

array: [6.  7.  8.4]
type of arr: float64


In [27]:
#we can also create a float array with integers by declaring a key word float
arr1=array([7,8,9],float)
print("array:",arr1)
print("type of arr1:",arr1.dtype)

array: [7. 8. 9.]
type of arr1: float64


In [28]:
my_list=[1,2,3]
x=np.array(my_list)
print(x)
type(x)

[1 2 3]


numpy.ndarray

## Creating Matrix by Arrays



In [29]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
# 3 columns and 3 rows 

# Exercise 

* Make a  3 by 4 matrix 
* Make a 6 by 6 matrix 
* Make a 2 by 6 matrix 

In [30]:
# result indicates that it is two dimensional matrix with 3 columns and 1 row
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
my_matrix=[[1,2,3,4],[5,6,6,7],[8,9,10,11]]
# 4 columns and 4 rows 

In [6]:
# result indicates that it is two dimensional matrix with 3 columns and 1 row
np.array(my_matrix)

array([[ 1,  2,  3,  4],
       [ 5,  6,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
my_matrix=[[1,2],[5,6],[8,9,], [3,4]]
# 2 columns and 4 rows 

In [8]:
# result indicates that it is two dimensional matrix with 3 columns and 1 row
np.array(my_matrix)

array([[1, 2],
       [5, 6],
       [8, 9],
       [3, 4]])

In [31]:
list(range(0,5))


[0, 1, 2, 3, 4]

In [14]:
np.arange(0,11)


array([ 0,  5, 10])

In [12]:
np.arange(1,21,3)
# 1, 13 is the array 
# 2 is the interval 


array([ 1,  4,  7, 10, 13, 16, 19])

* Way 5- Creating Arrays through Linear space

Linear Space will will create numbers between the given range. Distance between the numbers would be equal. In the example below will create 3 numbers betweeen 0 and 10 with equal distance

In [16]:
np.linspace(0,15,4)

array([ 0.,  5., 10., 15.])

In [17]:
np.arange(0,15,4)


array([ 0,  4,  8, 12])

In [18]:
#generate 30 numbers between 0 to 10
np.linspace(0,15,40)

array([ 0.        ,  0.38461538,  0.76923077,  1.15384615,  1.53846154,
        1.92307692,  2.30769231,  2.69230769,  3.07692308,  3.46153846,
        3.84615385,  4.23076923,  4.61538462,  5.        ,  5.38461538,
        5.76923077,  6.15384615,  6.53846154,  6.92307692,  7.30769231,
        7.69230769,  8.07692308,  8.46153846,  8.84615385,  9.23076923,
        9.61538462, 10.        , 10.38461538, 10.76923077, 11.15384615,
       11.53846154, 11.92307692, 12.30769231, 12.69230769, 13.07692308,
       13.46153846, 13.84615385, 14.23076923, 14.61538462, 15.        ])

## Exercise 

* Generate 50 numbers between 0 to 20 


In [20]:
"""if you don't specify the total number of items generated, 
it will automatically generates 50 numbers"""
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])